### PR TITLE
setting the install order of pending campaigns for one VIN also affects all other VIN-s

### PR DESCRIPTION
**Pull request by mgarciaberlin**
Depends on https://github.com/advancedtelematic/rvi_sota_server/pull/396

No change in the UI needed because the interface given by endpoints remains unchanged by this PR. Those endpoints are:
- PUT `api/v1/vehicle_updates/vin/order` , `VehicleUpdatesResource#setInstallOrder()`
- GET `api/v1/vehicle_updates` , `VehicleUpdatesResource#pendingPackages()`

### CODE REVIEW

**Comment by mgarciaberlin** [comment]
- Build 251 is green
- Build 250 (same contents) failed with Flyway migration,
http://teamcity.prod01.internal.advancedtelematic.com:8111/viewLog.html?buildId=3806&buildTypeId=ota_plus_RviSotaServer_CiTest

Just sayin.

**Comment by mgarciaberlin** [comment]
What's up?

**Comment by simao** [comment]
what are we trying to solve here?

**Comment by mgarciaberlin** [comment]
Details in https://advancedtelematic.atlassian.net/browse/PRO-485

**Comment by simao** [comment]
The premisse in that ticket is partially true, it does affect all updates for a vin, but in the current system we are creating an UpdateSpec+UpdateRequest for each update for each vin, so it does not have any effect.

**Pull request merged**
