### PR TITLE
add test for DigestCalculator, fix bug

### PR DESCRIPTION
**Pull request by simao**
Also, that squash on the PR is really not that great. I wanted to rebase
this branch on origin/master and now there is only one big commit with
those changes and looking at the history it's hard to say what happen,
there is not even a merge commit.

### CODE REVIEW

**Comment by koshelev** [comment]
It is our common strategy to squash commits. I have not seen any reason to keep commits in this case.
Any Idea why CI is failing?

**Comment by simao** [comment]
Squashing is fine, but not having a merge commit makes history hard to read and it doesn't look like our common strategy looking at the history. I don't know, some db issue unrelated, running again.

**Comment by koshelev** [comment]
Oh, I see. Valid point

**Comment by simao** [comment]
all green now.

**Pull request merged**
