### PR TITLE
Refactor/extract routes

### PR DESCRIPTION
**Pull request by simao**
Extract route methods on all resources/services so they can be reused downstream when using published jars.

### CODE REVIEW

**Comment by jerrytrieu** [comment]
To confirm the last case, a request with invalid auth and invalid path should result in 404?

**Comment by koshelev** [comment]
Invalid path 404, invalid authorization with a valid path - 403 Forbidden

**Comment by simao** [comment]
@jerrytrieu Extracted all core routes now, once this gets into master we can publish a jar and use it in core.

**Comment by jerrytrieu** [comment]
Looks good. The commit messages are a bit confusing. Squash?

**Comment by koshelev** [comment]
@jerrytrieu You can now squash on merge with github :)

**Comment by simao** [comment]
I didn't squash it because I think @rdanitz branched off this branch. @rdanitz can I squash this?

**Comment by rdanitz** [comment]
sure go ahead, my changes only touch external-resolver

**Comment by simao** [comment]
Ok squashed and green now.

**Pull request merged**
