### PR TITLE
change resolver to work with device_uuid instead of vin

### PR DESCRIPTION
**Pull request by simao**
https://advancedtelematic.atlassian.net/browse/PRO-808

### CODE REVIEW

**Comment by simao** [comment]
Along with the migrations for this, I also wrote a scala script to convert from vins to uuids, querying the device registry. This will run on startup if the relevant env variable is set.

I tested this migration with a db dump from stable (core, resolver, device registry) and it worked. I also tested with staging but the data in staging is all messed up, i.e., there are vehicles in resolver that are not in device registry and vice versa, so this migration will not work properly for all vehicles in staging.

After this migration runs in staging, we can delete it from the codebase.

**Comment by simao** [comment]
This requires some changes in ota-web, changes are ready but need this merged to master before ci can be green for ota.

**Comment by jerrytrieu** [comment]
Nice! We can wipe the messed staging db, and try the data migrate on stable tomorrow post-demo. Feel free to merge.

**Comment by jerrytrieu** [comment]
Score: 26/26

**Pull request merged**
