### PR TITLE
PK for slick mappings

### PR DESCRIPTION
**Pull request by mgarciaberlin**

### CODE REVIEW

**Comment by jerrytrieu** [comment]
Need rebase

**Comment by mgarciaberlin** [comment]
@simao Are there any known Slick issues with the following?
```diff
-    def id = column[UUID]("update_request_id", O.PrimaryKey)
+    def id = column[UUID]("update_request_id")
. . .
+    def pk = primaryKey("pk_UpdateRequest", (id))
```
Because I've standardized on "def pk"

**Comment by simao** [comment]
No, this should be equivalent AFAIK

**Comment by mgarciaberlin** [comment]
@simao This PR adds comments to one of the db migration files ( `V4__namespaces.sql` ) and thus changes its checksum. CI tests pass. But I hear "changing the checksum breaks migrations". Could you elaborate?

**Comment by simao** [comment]
CI passes because the migrations are all run from scratch on an empty db. If you merge this and try to run migrations on the server (staging/master) it will fail because the checksum is not the same.

**Comment by mgarciaberlin** [comment]
@simao ok, then I will revert the comments I added.

**Pull request merged**
