### PR TITLE
Make package id its own object in the json format in core, just like it

### PR DESCRIPTION
**Pull request by stevana**
already is in resolver. Requested by @calumats.

### CODE REVIEW

**Comment by stevana** [comment]
See PR #70 for a more long term fix.

**Comment by jerrytrieu** [comment]
Updating frontend in this PR?

**Comment by jerrytrieu** [comment]
@stevana can you update the frontend for this too?

**Comment by jerrytrieu** [comment]
And rebase off latest master.

**Comment by stevana** [comment]
This was basically a quick fix to make it possible for @calumats to get on with simplify the UI (he based his work on this branch). There's no need to merge this, as PR #70 contains the same changes without relying on spray-json.

**Pull request closed without merging**
