### PR TITLE
Replace packagesFor/filtersFor paths with a parametrised version of GET

### PR DESCRIPTION
**Pull request by stevana**
/packageFilters.

/cc @jerrytrieu

### CODE REVIEW

**Comment by stevana** [comment]
Also /cc @tkfu for documentation changes.

**Comment by stevana** [comment]
Retest this please.

**Comment by stevana** [comment]
Retest this please.

**Comment by jerrytrieu** [comment]
Need to update the frontend in this PR.

/cc @calumats

**Comment by calumats** [comment]
Ok, I'll update this PR once I've made the changes.

**Pull request merged**
