### PR TITLE
PRO-559 vehicles to devices in core

### PR DESCRIPTION
**Pull request by rdanitz**
use devices throughout core

- all references in core now use device uuids as unique identifiers;
  for now, if necessary, does a lookup for the device in the registry
- resolver keeps Vehicles and Vins
- Use real namespaces
- use common errorHandler instead of explicit completeWithRecover
- add device registry to docker compose
- change schema; unique key constraints for device_name and device_id
  only within namespace
- fix devices search
- separate authenticated routes in device registry
- fix device types in schema (numeration)
- search based on device name instead of device id

### CODE REVIEW

**Comment by rdanitz** [comment]
ready for primetime

**Comment by simao** [comment]
Needs rebase, doing it now. 

How is the deployment of ota+ device registry?

**Comment by tkfu** [comment]
API spec in docs will need to be updated, too. @rdanitz, do you want to make the changes yourself, or shall I do it? (If you do it, there's a readme in /docs/swagger)

**Comment by tkfu** [comment]
Some concerns about the docker-compose files.

- device_registry is added to the server-bare.yml docker-compose file, but needs to also be added in to server-rvi and server-rvi-client.
- What about database migrations for device_registry? Core and resolver run their own migrations at startup (CORE_DB_MIGRATE='true'), and have a startup script that waits for the database to be available before running them. Does device_registry need any migrations, or will it need them in future?

**Comment by rdanitz** [comment]
a checklist of files that need to be updated when adding a new service;
please correct me if i'm missing sth:

**in rvi_sota_server:**
- deploy/docker-compose/server-{bare, rvi, rvi-client}.yml – only referenced in docs; for user deployment (?)
- deploy/migration/{env, entrypoint.sh} for migration in ci (?)
- deploy/entrypoint-<new_service>.sh – waiting for db (?)
- deploy/ci_db_setup.sh – config db (?)
~~- deploy/deploy-sota-{debug, ec2, local}~~ – obsolete, using docker-launcher
~~- deploy/docker-launcher.yml.example~~ – obsolete, using docker-launcher
~~- deploy/sota-docker-hub/*~~ – obsolete, using docker-launcher

**in ota_plus_server:**
- docker/{common, precise}.yml – only referenced in docs, for user deployment (?)
- docker/{start-up.sh, teamcity.yml} – for ci

**Comment by simao** [comment]
I am rebasing this now.

**Comment by simao** [comment]
@rdanitz can u fix ci please? Then I'll rebase again.

**Comment by rdanitz** [comment]
@simao done

**Comment by simao** [comment]
Thanks, rebasing now

**Comment by simao** [comment]
done

**Comment by simao** [comment]
just fyi, this is how I did the rebase merging your rebase with my rebase `git rebase -i --onto origin/master refactor/vehicles-to-devices` and then discarding the commits that were already in master and squashing my big commit with your big commit. Worked better than I thought.

**Comment by mgarciaberlin** [comment]
This is shadowed and can be deleted
```diff
-import org.genivi.sota.datatype.Namespace
```
in `device-registry/src/test/scala/org/genivi/sota/device_registry/DeviceRequests.scala`

**Comment by jerrytrieu** [comment]
Let's merge this when ready. We can wipe staging now.

**Comment by simao** [comment]
This is "ready" to merge. It will probably break some things, but I thought we were ok with it?

**Comment by jerrytrieu** [comment]
Let's merge. Okay to break :)

**Comment by rdanitz** [comment]
one thing which is known to break:
provisioning of client and updates to `vehicle_updates/:vin` will not work, as the client will have to communicate with web/core with `:uuid` instead of `:vin`

**Comment by simao** [comment]
But will newly downloaded client debs use the new uuid?

**Comment by rdanitz** [comment]
this involves the buildserver i guess – as of now i'd say no /cc @taheris

**Comment by simao** [comment]
But the buildserver should just use the id web gives it. If web gives it a uuid, would it just use it? This is something we could test before merging.

**Comment by taheris** [comment]
Yes, Simao is right ([relevant src line](https://github.com/advancedtelematic/ota-plus-buildsrv/blob/master/src/srv.rs#L93)). There is no VIN validation done on the buildsrv side, so a UUID should work for now (which is not to say there won't be other breakages elsewhere, but these can be fixed).

**Pull request merged**
