### PR TITLE
Move PackageFiltersRepository into its own file.

### PR DESCRIPTION
**Pull request by stevana**

### CODE REVIEW

**Comment by stevana** [comment]
Stylecheck complains because of the new header...

   [Step 3/10] /var/lib/teamcity/TeamCity/buildAgent/work/24457b37eaf054ec/external-resolver/src/main/scala/org/genivi/sota/resolver/packages/PackageFilterRepository.scala:2: Header does not match expected text

I tried modifying the scalastyle config, but without luck... @koshelev ?

**Comment by stevana** [comment]
(I have no idea why this change to the style config works.)

**Comment by jerrytrieu** [comment]
It's not checking the new file? Try adding long lines to it...

**Comment by stevana** [comment]
It did before I made the changes to the config though? Does one need to reload the config somehow perhaps?

**Comment by jerrytrieu** [comment]
Ah, strange, the `scalastyle:off` seems to pass the header for me.

**Comment by stevana** [comment]
Good catch; I thought that line turned off the style checker from that line and onwards rather than the whole file?!

**Comment by stevana** [comment]
I removed the new header and created a separate ticket, SOTA-171.

**Pull request merged**
