### PR TITLE
Remove spray-json dependency from core.

### PR DESCRIPTION
**Pull request by stevana**

### CODE REVIEW

**Comment by stevana** [comment]
@tkfu spray-json seems to be mentioned in the docs as a dependency, this can be removed/changed to https://github.com/travisbrown/circe (which is the json library we currently use).

**Comment by stevana** [comment]
I doubt those tests fail because of my changes -- they pass fine locally...

**Comment by koshelev** [comment]
Not on my box

**Comment by stevana** [comment]
Rebased.

**Pull request merged**
