### PR TITLE
Fix/db schema

### PR DESCRIPTION
**Pull request by stevana**

### CODE REVIEW

**Comment by stevana** [comment]
Needs flywayRepair or whatever on TC, as I merged all migration files...

**Comment by jerrytrieu** [comment]
Rebased and running flywayRepair on tc now. Will add note in docs.

**Comment by jerrytrieu** [comment]
Missing the schema sql in resolver?

**Comment by stevana** [comment]
Yep, fixed.

**Comment by stevana** [comment]
@jerrytrieu: We got this working locally on @calumats' machine, so it seems to be some random TC bs (@calumats says the integration tests on TC have magically stopped working several times before)...

**Comment by jerrytrieu** [comment]
//cc @tkfu can you update docs?

Run `./sbt flywayClean` if `./sbt flywayMigrate` complains about checksum error.

**Comment by tkfu** [comment]
Added the troubleshooting step, but I think I'm going to make a general troubleshooting page in a separate PR. We've got a bunch of little notes/fixes at a bunch of places in the docs; it would be good to have them all in one place and just link from the main pages where they apply.

**Pull request merged**
