### PR TITLE
Feat/device registry

### PR DESCRIPTION
**Pull request by rdanitz**
micro-service to handle creation, attributes and matching between id's and deviceId's

### CODE REVIEW

**Comment by rdanitz** [comment]
ready to merge; please have a thorough look especially on API and spec!
things that are missing:
- publishing to event bus
- secret and key in schema
/cc @koshelev

**Comment by jerrytrieu** [comment]
Is this causing 45+ mins on tc?

**Comment by mgarciaberlin** [comment]
```
[Step 5/10] org.genivi.sota.resolver.test.Random (25m:49s)
```

**Comment by jerrytrieu** [comment]
Was that changed in recent PR? Can you shorten?

**Comment by mgarciaberlin** [comment]
The last change to the fuzzer was adding checks for "bad requests" in https://github.com/advancedtelematic/rvi_sota_server/pull/353

However at the time that test took "only" 11 minutes. Not sure if that was a straddler on the low end, or whether the hardware got slower in the meantime. Any reduction in fuzzer running time (which is doable) amounts to leaving out some "coverage" (for example, by being ok with say 50% coverage of "bad requests").

BTW, there's another notable contributor:
```
Step 2/10: Migrations (Simple Build Tool (Scala)) (9m:25s)

```

**Comment by mgarciaberlin** [comment]
Perhaps the hardware did get slower. In #353 we had instead of 11 minutes today:
```
Step 2/10: Migrations (Simple Build Tool (Scala)) (1m:58s)
```

**Comment by jerrytrieu** [comment]
Okay. Gonna merge this.

**Pull request merged**
