### PR TITLE
Slick 3.1.1, MariaDB JConnector 1.4.4

### PR DESCRIPTION
**Pull request by mgarciaberlin**
I haven't tested locally, need CI build for testing.

### CODE REVIEW

**Comment by mgarciaberlin** [comment]
Perhaps @stevana can give feedback on the fuzzer-related changes, and @koshelev on the sbt-related changes.

**Comment by mgarciaberlin** [comment]
This PR is from last week.

**Comment by jerrytrieu** [comment]
Let's merge after #385. Can you squash some commits?

**Comment by jerrytrieu** [comment]
Can rebase and squash

**Pull request merged**
