### PR TITLE
Rename device-registry in docker-compose

### PR DESCRIPTION
**Pull request by alexhumphreys**

### CODE REVIEW

**Comment by alexhumphreys** [comment]
I'm trying to add the rvi_sota_server to the ota-integration-builder, and I think to get a clean path through all the PRs to make that happen I need to have device_registry start up with `-` instead of `_`.

**Comment by jerrytrieu** [comment]
The project and docker image is device_registry. Rename those too?

**Comment by jerrytrieu** [comment]
:+1:

**Comment by alexhumphreys** [comment]
Sorry, merged before I saw the first comment. I basically just need the containers to be `-`, but we can change the rest of the names too if you like. Might need to change things in nexus, dockerhub, etc so I'm not entirely sure how far that change goes...

**Pull request merged**
