### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by simao**

### CODE REVIEW

**Comment by simao** [comment]
cc @rdanitz

**Comment by jerrytrieu** [comment]
Need to merge this?

**Comment by simao** [comment]
This should have been merged in @rdanitz's branch?

**Comment by jerrytrieu** [comment]
Let's rebase and merge this now?

**Comment by simao** [comment]
I am not sure this is still needed, because it made tests green, and tests are green. @rdanitz ?

**Comment by rdanitz** [comment]
i'll rebase and check everything

**Comment by rdanitz** [comment]
after rebasing the commit is empty.
i'll close …

**Pull request closed without merging**
