### PR TITLE
Feat/device names

### PR DESCRIPTION
**Pull request by rdanitz**

### CODE REVIEW

**Comment by mgarciaberlin** [comment]
I also had to increase the timeout, the following seems to works: https://github.com/advancedtelematic/rvi_sota_server/pull/391/commits/8f449c77f1c3b2f43cba1ce19b97a4c316b10ea2

**Comment by rdanitz** [comment]
The patience didn't do it for me …
`implicit val patience = PatienceConfig(timeout = Span(5, Seconds), interval = Span(500, Millis))` still results in `Request was neither completed nor rejected within 1 second` which suggests, that both timeouts are not compatible?

**Comment by jerrytrieu** [comment]
Need rebase.

**Comment by jerrytrieu** [comment]
Looks like nearly empty commit 0f6aa5461d1 duplicates previous PR. Can you squash?

**Pull request merged**
