### PR TITLE
PRO-602 Update docs with new history endpoint location

### PR DESCRIPTION
**Pull request by calumats**
Unfortunately I couldn't get the docs building on my machine, any chance you could do the honours when you get a chance Jon?

### CODE REVIEW

**Comment by calumats** [comment]
@tkfu Just realized I didn't tag you in the last comment. Any chance you could generate the docs for me?

**Comment by jerrytrieu** [comment]
To confirm, does the webserver UI use this endpoint?

**Comment by calumats** [comment]
Yes, AFAIK it does.

**Comment by tkfu** [comment]
This is superseded by the new swagger docs, so it no longer needs to get merged in.

**Pull request closed without merging**
