### PR TITLE
PRO-589 core: readability of VehicleDirectives

### PR DESCRIPTION
**Pull request by mgarciaberlin**
Ticket: https://advancedtelematic.atlassian.net/browse/PRO-589

### CODE REVIEW

**Comment by simao** [comment]
Think I am missing something here, don't understand what is different from master? I think the problem now is that I couldn't update ota server to use latest sota master, should be working after the merge? Otherwise I don't understand what is the difference on this commit?

**Comment by mgarciaberlin** [comment]
- Commit 	1f7f7bb is formatting only
- Commit 207cee5 groups the routes on two criteria: First, by common prefix; Second by namespace requirement.

Previously the grouping was by: First, routes requiring namespace. Second, common prefix.

Let's talk tomorrow about what differences that might entail (besides readability).

**Comment by simao** [comment]
Ok, this only affects readability (which I agree it's better). because the extract uses `reject` and not `complete`, so akka still tries the next routes. I just upgraded sota on ota, so maybe the ticket is solved once it's deployed?

**Comment by simao** [comment]
Ok, @alexhumphreys I created a vin, went through the pain of creating auth plus tokens and basic authing with auth plus, posted packages and now it seems to work with latest master, could you try again?

Thanks.

**Comment by mgarciaberlin** [comment]
Ah, ok. The original bug was already fixed, and this PR is about readability. I've changed the title for this PR's ticket to reflect that.

**Comment by alexhumphreys** [comment]
@simao any chance you can tell me the commands you ran for that?

**Comment by mgarciaberlin** [comment]
Commit 	18b282b is there to avoid a transient compilation error. It happened twice, might happen again.

Details below, full details at http://teamcity.prod01.internal.advancedtelematic.com:8111/viewLog.html?buildId=4242&buildTypeId=ota_plus_RviSotaServer_Ci

Yes, looks like the interplay with macros makes scalac non-deterministic.

```
common/src/main/scala/org/genivi/sota/datatype/NamespaceDirective.scala:26: exception during macro expansion: 
java.lang.AssertionError: assertion failed: import failure: cannot determine unique overloaded method alternative from
 final package eu
final package eu
 that matches package eu:eu.type
. . .

-  private lazy val defaultConfigNamespace: Namespace =
 -    configNamespace(ConfigFactory.load()).getOrElse("default-config-ns")
 +  private lazy val defaultConfigNamespace: Namespace = {
 +    configNamespace(ConfigFactory.load()) getOrElse {
 +      val nsE: Either[String, Namespace] = refineV("default-config-ns")
 +      nsE.right.toOption.get
 +    }
 +  }

**Comment by simao** [comment]
Yes, here it is https://gist.github.com/simao/fdf81aa426546bf84e928be33e0e6064

**Pull request merged**
