### PR TITLE
Random test now passes with "only" 100 successful trials

### PR DESCRIPTION
**Pull request by mgarciaberlin**
After looking at the effect on CI build time, it'll be easier to gauge whether this PR should be merged.

### CODE REVIEW

**Comment by mgarciaberlin** [comment]
Making `Random` faster is all fine, however other contributors can be singled out. For example:
- one week ago: `Step 8/10: Compose Up (Command Line) (21s)`
- today: `Step 8/10: Compose Up (Command Line) (3m:15s)`

**Comment by simao** [comment]
@mgarciaberlin what do you mean?

**Comment by mgarciaberlin** [comment]
```
org.scalatest.prop.Configuration
class PropertyCheckConfig
...
   * @param minSuccessful the minimum number of 
                          successful property evaluations required for 
                          the property to pass.
```

The `property("Sessions")` in https://github.com/advancedtelematic/rvi_sota_server/blob/master/external-resolver/src/test/scala/org/genivi/sota/resolver/test/Random.scala#L85 
is driven by that configuration, which now requires a lower number of successful (randomly generated) trials to be fulfilled (100 instead of 200).

**Comment by simao** [comment]
Yeah I know, but what do you mean by your comment above?

**Comment by mgarciaberlin** [comment]
The comment:
> Making `Random` faster is all fine, however other contributors can be singled out. For example:
> - one week ago: `Step 8/10: Compose Up (Command Line) (21s)`
> - today: `Step 8/10: Compose Up (Command Line) (3m:15s)`

highlights that step got slower.
Not clear to me why over 3 min are needed when previously 21 seconds were enough.

**Comment by simao** [comment]
There are many possible reasons, for example, each time an agent starts it doesn't have the docker images downloaded, so it needs to pull them from docker hub, so it takes more time.

**Pull request merged**
